### ISSUE TITLE
Do I have to create local `.env` file?

### ISSUE THREAD

**Issue by best-lucky1030** [Infvyr/nextjs-portfolio#2]
Hi @Infvyr 
I cloned and forked your repo and run on my side.
Btw, running the project, do I have to create `.env` file on my local side?
Seems like without that, it works well.

**Comment by Infvyr** [comment]
Hi, @best-lucky1030,
No, it's not quite necessary to create **.env**, but if you want to have the _Latest projects_ section active you have to follow the steps from [Readme](https://github.com/Infvyr/nextjs-portfolio#settings).
Also you should have installed [sanity](https://www.sanity.io/docs) globally and run `npm install` from sanity folder.

**Comment by best-lucky1030** [comment]
ok. gotcha.
thx @Infvyr
