### ISSUE TITLE
A steps in Sanity

### ISSUE THREAD

**Issue by mzmznasipadang** [Infvyr/nextjs-portfolio#4]
Hey Vasile,

I wonder if there is any Wiki or steps to get started with the Sanity? Thank you!

Nice Website though, it's a great web!

**Comment by vasile-novatchii** [comment]
Hey, friend,

You could read Sanity docs at https://www.sanity.io/docs/getting-started-with-sanity-cli or just watch any youtube video on this topic. It's pretty simple. You also should read about sanity studio.

**Comment by mzmznasipadang** [comment]
Thank you! I will look into it!



Victor Chandra
Information Systems
BINUS University Alam Sutera

M: +62 87729072000 <https://wa.me/6287729072000>
E: ***@***.******@***.***>
binus.ac.id<https://www.mail-signatures.com/signature-generator/binus.ac.id>

South Tangerang, Banten, Indonesia

The content of this email is confidential and intended for the recipient specified in message only. It is strictly forbidden to share any part of this message with any third party, without a written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.

________________________________
