### ISSUE TITLE
Theme toggle does not work for the first time

### ISSUE THREAD

**Issue by RaviSolanki27** [Infvyr/nextjs-portfolio#9]
- Once the page is loaded, then you will click on the theme toggle button. When clicking for the first time, it will not work but then clicking again it will work properly as the theme mode is saved in the local storage. This issue will not occur after refresh. But if you clear local storage and then refresh, this issue will happen again.

**Comment by vasile-novatchii** [comment]
Thank you for noticing this small issue! I've just deployed a new release where I fixed this issue. Would be nice of you to confirm that the issue is fixed.
